<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Version>1.0.2</Version>
    <Product>GIBS.Module.TextMe</Product>
    <Authors>Joseph M Aucoin</Authors>
    <Company>GIBS</Company>
    <Description>Twilio TextMe Module for Oqtane</Description>
    <Copyright>GIBS</Copyright>
    <AssemblyName>GIBS.Module.TextMe.Server.Oqtane</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <StaticWebAssetsFingerprintContent>false</StaticWebAssetsFingerprintContent>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\_content\**\*.*" />
    <None Include="wwwroot\_content\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Twilio.AspNet.Core" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\GIBS.Module.TextMe.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Oqtane.Server"><HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\net10.0\Oqtane.Server.dll</HintPath></Reference>
    <Reference Include="Oqtane.Shared"><HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\net10.0\Oqtane.Shared.dll</HintPath></Reference>
  </ItemGroup>
</Project>
